stages:
  - build
  - test
  - package
  - deploy

variables:
  maven_packages_cache: ".m2/repository"
  MAVEN_OPTS: "-Dmaven.repo.local=./$maven_packages_cache"

build:
  stage: build
  tags:
    - docker
  cache:
    paths:
      - $maven_packages_cache
  script:
    - mvn compile
  artifacts:
    paths:
      - "target/*"
    expire_in: 1 week

test:
  stage: test
  tags:
    - docker
  dependencies:
    - build
  cache:
    paths:
      - $maven_packages_cache
  script:
    - mvn test

package:
  stage: package
  tags:
    - docker
  dependencies:
    - build
  script:
    - mvn package
  artifacts:
    paths:
      - "target/*.war"
    expire_in: 1 week

deploy:
  stage: deploy
  tags:
    - shell
  dependencies:
    - package
  when: manual
  environment:
    name: "deploy game"
    url: "http://localhost:8080/game2048"
    action: start
    on_stop: stop_server
  script:
    - docker rm --force tomcat
    - docker image rm --force game2048
    - echo -e 'FROM tomcat:9.0.46-jdk11 \n COPY ./target/game2048.war /usr/local/tomcat/webapps' | docker build -t game2048 -f- .
    - docker run --rm -d --name tomcat -p 8080:8080 game2048

stop_server:
  stage: deploy
  tags:
    - shell
  when: manual
  environment:
    name: "deploy game"
    action: stop
  script:
    - docker rm --force tomcat
    - docker image rm --force game2048