name: gam2048-workflow
on: [push]
jobs:
  build:
    name: Build
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - name: Build Project
        run: mvn compile
  test:
    name: Test
    runs-on: [self-hosted, linux]
    needs: build
    steps:
      - name: Execute Unit Tests
        run: mvn test
  package:
    name: Package
    runs-on: [self-hosted, linux]
    needs: test
    steps:
      - name: Package Application
        run: mvn package
      - uses: actions/upload-artifact@v2
        with:
          name: game2048.war
          path: "target/game2048.war"
  deploy:
    name: Deploy
    runs-on: [self-hosted, linux]
    needs: package
    steps:
      - name: Download Package File
        uses: actions/download-artifact@v2
        with:
          name: "target/game20248.war"
      - name: Copy Package
        run: "cp game2048.war /usr/local/tomcat/webapps"
  