name: gam2048-workflow
on: [push]
jobs:
  build:
    name: Build
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - name: Build Project
        run: mvn compile
  test:
    name: Test
    runs-on: [self-hosted, linux]
    needs: build
    steps:
      - name: Execute Unit Tests
        run: mvn test
  package:
    name: Package
    runs-on: [self-hosted, linux]
    needs: test
    steps:
      - name: Package Application
        run: mvn package
      - uses: actions/upload-artifact@v2
        with:
          path: "target/*.war"
  deploy:
    name: Deploy
    runs-on: [self-hosted, linux]
    needs: package
    steps:
      - name: Remove container
        run: docker rm --force tomcat
      - name: Remove image
        run: docker image rm --force game2048
      - name: Create container
        run: echo -e 'FROM tomcat:9.0.46-jdk11 \n COPY ./target/game2048.war /usr/local/tomcat/webapps' | docker build -t game2048 -f- .
      - name: Run container
        run: docker run --rm -d --name tomcat -p 8080:8080 game2048
  